# Generated by Django 5.1.4 on 2025-01-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooditems', '0008_cartitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
